/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HcwCama {
    }
    interface UcSideDrawer {
        "open": boolean;
        "title": string;
    }
}
declare global {
    interface HTMLHcwCamaElement extends Components.HcwCama, HTMLStencilElement {
    }
    var HTMLHcwCamaElement: {
        prototype: HTMLHcwCamaElement;
        new (): HTMLHcwCamaElement;
    };
    interface HTMLUcSideDrawerElement extends Components.UcSideDrawer, HTMLStencilElement {
    }
    var HTMLUcSideDrawerElement: {
        prototype: HTMLUcSideDrawerElement;
        new (): HTMLUcSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "hcw-cama": HTMLHcwCamaElement;
        "uc-side-drawer": HTMLUcSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface HcwCama {
    }
    interface UcSideDrawer {
        "open"?: boolean;
        "title"?: string;
    }
    interface IntrinsicElements {
        "hcw-cama": HcwCama;
        "uc-side-drawer": UcSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hcw-cama": LocalJSX.HcwCama & JSXBase.HTMLAttributes<HTMLHcwCamaElement>;
            "uc-side-drawer": LocalJSX.UcSideDrawer & JSXBase.HTMLAttributes<HTMLUcSideDrawerElement>;
        }
    }
}
